Expose publish_override_ok via APIs
hysds/mozart pull request #50
Opened 2023-05-22 22:57 UTC by joshgarde

Part of HC-473 work

2024-03-14 22:00 UTC, pymonger approved these changes, later dismissed
LGTM but let's get another pair of eyes.

2024-03-14 22:08 UTC, mcayanan requested changes
Should we do a version bump to 2.3.1?

https://github.com/hysds/mozart/blob/6a73c614cebdfe959529b64a3464502e014c8856/setup.py#L12

2024-03-14 23:11 UTC, mcayanan commented
@joshgarde looks good. However, it looks like there's a conflict with setup.py. When you can, could you please resolve?

2024-03-15 00:09 UTC, pymonger approved these changes

2024-03-15 00:10 UTC, mcayanan approved these changes

2024-03-15 00:11 UTC, mcayanan approved these changes

2024-03-15 00:15 UTC, DustinKLo approved these changes

2024-03-15 00:59 UTC, merged